version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    links:
      - db
    command:
      sh -c "sleep 5 && node server.js"

  db:
    image: mongo
    ports:
      - 27017:27017
